### ISSUE TITLE
Regression in 7.5.6: gRPC responses decode with undefined code/details/empty metadata when used via @grpc/grpc-js / google-gax

### ISSUE THREAD

**Issue by ekansh-tdc** [protobufjs/protobuf.js#2214]
After upgrading protobufjs from 7.5.5 → 7.5.6 (and its sub-deps @protobufjs/codegen 2.0.4→2.0.5, @protobufjs/inquire 1.1.0→1.1.1, @protobufjs/utf8 1.1.0→1.1.1), gRPC unary calls made through @google-cloud/run's JobsClient started failing with an Error whose code, details, and metadata fields are all undefined / empty. Pinning protobufjs back to 7.5.5 resolves the issue.

Environment
protobufjs: 7.5.6 (broken) / 7.5.5 (works)
@google-cloud/run: 3.2.0 (unchanged)
@grpc/grpc-js: unchanged across the regression
google-gax, google-auth-library, gaxios, gtoken: all unchanged
Node.js: (fill in your prod Node version)
Runtime: Google Cloud Run (Next.js 16 server)
Package manager: bun (lockfile-resolved)
The lockfile diff shows protobufjs and its sub-modules are the only packages in the gRPC request path that changed between the working and broken states.

Symptom
Calling JobsClient.runJob(...) produces:

Error: undefined undefined: undefined
    at <anonymous> (.../grpc-js)
    at onReceiveStatus (.../grpc-js)
    at onReceiveStatus (.../grpc-js)
    at onReceiveStatus (.../grpc-js)
    ... (gRPC client internals)
    at makeUnaryRequest (.../grpc-js)
    ...
{
  code: undefined,
  details: undefined,
  metadata: Metadata { internalRepr: Map(0) {}, opaqueData: Map(0) {}, options: {} }
}
The thrown ServiceError has no status code, no details, and an empty metadata map — i.e. the trailers/status frame is being decoded into empty/undefined fields rather than being parsed correctly. A normal RPC failure carries a numeric code (e.g. 7 PERMISSION_DENIED) and a details string; an auth/transport failure usually surfaces as a different bare Error. This signature is distinct from both.

Reproduction
Minimal repro:

```
import { JobsClient } from '@google-cloud/run'

const client = new JobsClient()
await client.runJob({
  name: client.jobPath('my-project', 'us-central1', 'my-job')
})
```

Run on Cloud Run with protobufjs@7.5.6 resolved in the tree → throws the all-undefined error.
Pin protobufjs@7.5.5 (e.g. via "resolutions" / "overrides") → call succeeds.

Suspected cause
@google-cloud/run → google-gax → @grpc/grpc-js all rely on protobufjs to decode the gRPC trailing status frame. The fact that the decoded status object has code: undefined, details: undefined and an empty metadata Map suggests the trailer decode is silently producing an empty/zero-initialized object rather than throwing. Possibly related to the @protobufjs/codegen 2.0.4→2.0.5 or @protobufjs/utf8 1.1.0→1.1.1 patch (the latter could affect string field decoding in the status message).

Workaround
Pin protobufjs to 7.5.5:

package.json
```
{
  "overrides": {
    "protobufjs": "7.5.5"
  }
}
```

**Comment by dcodeIO** [comment]
Could be a bad bundler/runtime interaction with the updated `@protobufjs/inquire` micromodule.

`@protobufjs/inquire@1.1.1` changed the optional require path from hidden `eval("require")` to a direct dynamic `require(moduleName)`:

```js
// 1.1.0
var mod = eval("quire".replace(/^/,"re"))(moduleName);

// 1.1.1
if (typeof require !== "function") return null;
var mod = require(moduleName);
```

That module is used by protobufjs to discover optional Node modules like buffer, long, and fs, so it is a plausible place for bundlers to diverge.

Could you try pinning only that package back to `1.1.0` while keeping `protobufjs@7.5.6`?

```json
{
  "overrides": {
    "@protobufjs/inquire": "1.1.0"
  }
}
```

If that fixes it, the regression is likely in the `inquire` publish/bundler interaction rather than protobuf decoding itself.

**Comment by submarines-and** [comment]
For us, overriding only `@protobufjs/inquire` as suggested solves the problem for now.

For yarn:

```
  "resolutions": {
    "@protobufjs/inquire": "1.1.0"
  }
```

**Comment by gavinsharp** [comment]
Confirming the same regression with `@google-cloud/firestore@8.3.0` on Next.js 16 + Turbopack. The `"@protobufjs/inquire": "1.1.0"` override fixes it for us.

**Mechanism**: Turbopack rewrites the new `require(moduleName)` into a synchronous `throw MODULE_NOT_FOUND` IIFE, so every `inquire(...)` returns `null` at runtime — `util.Buffer`, `util.fs`, `util.Long` all unset. With `util.Buffer = null`, protobufjs encodes to `Uint8Array` instead of `Buffer`, which trips `@grpc/grpc-js`'s compression filter (it calls `message.copy(...)`, a Buffer-only method). The resulting `TypeError` propagates as `cancelWithStatus(undefined, undefined)`, producing the all-undefined empty status.

The `1.1.0` `eval`-based form survives Turbopack untouched because `eval(...)` is opaque to static analysis, and at runtime direct eval finds Node's `require` via the scope chain.

**Impact**: for server-streaming RPCs under gax retry (e.g. Firestore `query.get()`), each attempt fails instantly and the gax + SDK retry layers stretch it to **~45 s per request** — caused a 50-minute production outage for us when a Dependabot bump landed.

There's also a latent `@grpc/grpc-js` bug here (silent-failure path on non-status rejections); I'll file that separately.

**Comment by dcodeIO** [comment]
One option here is to backport #2237 to 7.x, which does `require("fs")` instead of `require(moduleName)` for the respective modules and obtains `Buffer` from the global object. Does that look good to ya'll?

**Comment by dcodeIO** [comment]
The bundler-safe module lookups have been backported to v7.5.9. The inquire module is no longer used there. See the original PR #2237 for details. Hence closing, but feel free to reopen if there are remaining issues.

**Comment by mtvx** [comment]
@dcodeIO Compilation still raises a warning on `protobufjs` v7.5.6+, those pull `@protobufjs/inquire` 1.1.1+.

Is pinning `@protobufjs/inquire` to 1.1.0 still required, or should things work with 1.1.2 now?

```
$ CI=true yarn build
Treating warnings as errors because process.env.CI = true.


Error: Failed to compile '../../node_modules/@protobufjs/inquire/index.js':
  ⚠ Critical dependency: the request of a dependency is an expression
    ╭─[16:22]
 14 │       return null;
 15 │     }
 16 │     var mod = require(moduleName);
    ·                       ──────────
 17 │     if (mod && (mod.length || Object.keys(mod).length)) return mod;
 18 │     return null;
    ╰────
```

Sorry, not a JS expert 🤷🏻‍♂️

**Comment by dcodeIO** [comment]
Since v7.5.9, inquire is still kept as a dependency and present as `util.inquire` with the `require(moduleName)` pattern, but nothing in protobuf.js calls it anymore. My expectation was that this would resolve the issue, but if it doesn't, a follow-up fix would be to remove the dependency and `util.inquire` entirely regardless of technically being a breaking API change.

**Comment by mtvx** [comment]
I'm not sure which bit ends up calling it, but here's the dependency tree for `protobufjs`:

```
❯ yarn why protobufjs
├─ @asyncapi/protobuf-schema-parser@npm:3.5.1
│  └─ protobufjs@npm:7.6.2 (via npm:^7.4.0)
│
├─ @google-cloud/firestore@npm:7.11.1
│  └─ protobufjs@npm:7.6.2 (via npm:^7.2.6)
│
├─ @grpc/proto-loader@npm:0.7.15
│  └─ protobufjs@npm:7.6.2 (via npm:^7.2.5)
│
├─ @grpc/proto-loader@npm:0.8.1
│  └─ protobufjs@npm:7.6.2 (via npm:^7.5.5)
│
├─ dockerode@npm:4.0.9
│  └─ protobufjs@npm:7.6.2 (via npm:^7.3.2)
│
├─ google-gax@npm:4.6.1
│  └─ protobufjs@npm:7.6.2 (via npm:^7.3.2)
│
├─ infinispan@npm:0.12.0
│  └─ protobufjs@npm:7.6.2 (via npm:^7.0.0)
│
└─ proto3-json-serializer@npm:2.0.2
   └─ protobufjs@npm:7.6.2 (via npm:^7.2.5)
```

And for `@protobufjs/inquire` (after locking it to 1.1.0 as a workaround):

```
❯ yarn why @protobufjs/inquire
└─ protobufjs@npm:7.6.2
   └─ @protobufjs/inquire@npm:1.1.0 (via npm:1.1.0)
```

Doesn't that mean nothing else can call `@protobufjs/inquire` except `protobufjs`?

**Comment by mtvx** [comment]
What's the harm in pinning `@protobufjs/iniquire` to 1.1.0 on `protobufjs` 7.5.6+? E.g. 7.6.2 sets version range to `^1.1.2` for `@protobufjs/inquire`.

**Comment by mtvx** [comment]
~The warning gets thrown when building a _frontend_ module (Backstage's frontend app). Maybe the reason that it's for browser makes an impact here? `webpack` somehow involved?~

Nevermind, the warning also appears when building the backend module 🤷🏻‍♂️
